# Generated by Django 4.1.7 on 2023-09-08 19:26

import compras.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CompraCabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(blank=True, default=compras.models.get_today, null=True)),
                ('fecha_aprobado', models.DateField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('fecha_cerrado', models.DateField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobado'), ('E', 'Entregado'), ('C', 'Cerrado')], default='P', max_length=1)),
                ('asignado_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignado_a', to=settings.AUTH_USER_MODEL)),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categoria_id', to='compras.categoria')),
                ('usuario_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_entrega', to=settings.AUTH_USER_MODEL)),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_registro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('puede_aprobar_compra', 'puede_aprobar_compra'), ('puede_entregar_compra', 'puede_entregar_compra'), ('puede_cerrar_compra', 'puede_cerrar_compra'), ('puede_ver_todas_las_compras', 'puede_ver_todas_las_compras'), ('puede_ser_aprobador', 'puede_ser_aprobador'), ('puede_ser_entregador', 'puede_ser_entregador')],
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(blank=True, max_length=250, null=True)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField()),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.categoria')),
                ('compra_cabecera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.compracabecera')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('puede_ver_categoria', 'puede_ver_categoria')],
            },
        ),
    ]
