# Generated by Django 4.1.7 on 2023-09-11 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compracabecera',
            name='usuario_aprobado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_aprobado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compracabecera',
            name='usuario_autorizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_autorizado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compracabecera',
            name='estado',
            field=models.CharField(choices=[('0', 'Pendiente'), ('1', 'Registrado'), ('2', 'Aprobado Encargado'), ('3', 'Autorizado Gerencia'), ('4', 'Entregado'), ('5', 'Cerrado')], default='P', max_length=1),
        ),
        migrations.CreateModel(
            name='UsuarioEncargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encargado', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
