# Generated by Django 4.1.7 on 2023-09-11 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_remove_compradetalle_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compradetalle',
            name='observaciones',
        ),
    ]
