# Generated by Django 4.1.7 on 2023-09-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_remove_compradetalle_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='compracabecera',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
