# Generated by Django 4.1.7 on 2023-09-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_compracabecera_usuario_rechaza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compracabecera',
            name='fecha_autorizado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
