# Generated by Django 4.1.7 on 2023-09-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_compracabecera_fecha_autorizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='compracabecera',
            name='valor_entregado',
            field=models.IntegerField(default=0),
        ),
    ]
