# Generated by Django 4.1.7 on 2023-09-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_compracabecera_valor_entregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='compracabecera',
            name='valor_real',
            field=models.IntegerField(default=0),
        ),
    ]
